Add GD32VF103 boards
KevinMX/support-matrix pull request #12
Opened 2024-05-07 09:10 UTC by wychlw

MCU200T是纯FPGA，DDR200T同款FPGA外挂GD32

2024-05-08 11:09 UTC, KevinMX requested changes
Some small typos found?
:)

2024-05-08 11:09 UTC, KevinMX commented on Longan_Nano/FreeRTOS/README.md
> +- RV-STAR 开发板（GD32VF103VBT6）
RV-STAR?

2024-05-08 11:09 UTC, KevinMX commented on Longan_Nano/FreeRTOS/README.md
> +# FreeRTOS RV-STAR 测试报告
RV-STAR?

2024-05-08 11:09 UTC, KevinMX commented on Longan_Nano/RT-Thread/README.md
> +# RT-Thread RV-STAR 测试报告
RV-STAR?

2024-05-08 11:09 UTC, KevinMX commented on Longan_Nano/RT-Thread/README.md
> +- RV-STAR 开发板（GD32VF103VBT6）
Same here

2024-05-08 11:09 UTC, KevinMX commented on README.md
> +| GD32VF103| [Longan Nano][Longan_Nano]       | N/A        | N/A           | N/A    | N/A     | N/A    | N/A        | N/A     | N/A         | N/A       | N/A       | N/A      | N/A    | N/A        |
Zehpyr Basic -> CFT?

2024-05-09 01:47 UTC, wychlw commented on README.md
> +| GD32VF103| [Longan Nano][Longan_Nano]       | N/A        | N/A           | N/A    | N/A     | N/A    | N/A        | N/A     | N/A         | N/A       | N/A       | N/A      | N/A    | N/A        |
Longan的Zephyr确实是之前测过的，这次和别的103一起加了前两个

2024-05-09 01:51 UTC, wychlw commented on Longan_Nano/RT-Thread/README.md
> +- RV-STAR 开发板（GD32VF103VBT6）
fixed all above

2024-05-09 03:39 UTC, KevinMX approved these changes

2024-05-09 03:39 UTC, merged