Translation for several board and some minor fix
KevinMX/support-matrix pull request #22
Opened 2024-06-13 02:16 UTC by wychlw

- Fix and tweaked translation for LicheePi4A, LicheeCluster4A and LicheeConsole4A.

- Fix some link and format issue

2024-06-13 09:26 UTC, wychlw commented
Mayby ready? I tried to correct where I can find out.

2024-06-14 07:44 UTC, KevinMX commented
> Mayby ready? I tried to correct where I can find out.

Has been busy on other stuff these days. Will review later.

2024-06-21 05:04 UTC, KevinMX requested changes

2024-06-21 05:04 UTC, KevinMX commented on BeagleV-Ahead/Ubuntu/README.md
> +### Boot Messages
Inconsistent translation (Boot Messages / Boot Information / Boot Log?)

2024-06-21 05:04 UTC, KevinMX commented on 100ASK/Melis/README.md
> +### Boot Information
I suggest "Boot log".

2024-06-21 05:04 UTC, KevinMX commented on BeagleV-Fire/Ubuntu/README_zh.md
> +**升级 Gateway 可直接在板上自带 Linux 中进行**，见[官方文档](https://docs.beagleboard.org/latest/boards/beaglev/fire/demos-and-tutorials/gateware/upgrade-gateware.html)
Gateway / Gateware?

2024-06-21 05:04 UTC, KevinMX commented on CH32V103/Zephyr/README.md
Deleted?

2024-06-21 05:04 UTC, KevinMX commented on BeagleV-Fire/Ubuntu/README.md
> +### Flashing Gateway Module
Gateway or Gateware?

2024-06-21 05:04 UTC, KevinMX commented on LicheeCluster4A/Fedora/README.md
> +    - or LPi4A Baseboard
Baseboard -> Dock/Motherboard?

2024-06-21 05:04 UTC, KevinMX commented on LicheePi4A/README.md
> +### Hardware Development Board Information
-> Board Information?

2024-06-21 05:57 UTC, merged